

TMPL_PANDOC_OPTS =  --variable=docintropath:"." --variable=docpath:doc 
PANDOC_OPTS =  --variable=doc:true --variable=docintropath:"." --variable=docpath:doc

TMPL_PANDOC_OPTS = $(PANDOC_OPTS)

# Build the documentation overview page (index.html)
include ../topic.mk

